# <p style="text-align: center;">Insee GPS</p>

## Import libraries

In [1]:
import pandas as pd
import numpy as np

import glob
import os

import requests

import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

## Set parameters

In [2]:
decree_filename_base = 'arrete_'
decrees_folder_name = './../../data/raw/decrees'
communes_folder_name = './../../data/raw/laposte'
processed_data_folder_name = './../../data/processed'
decrees_filename = 'decrees.parquet'
communes_csv_filename = '019HexaSmal-full.csv'

In [3]:
(os.path.join(communes_folder_name, communes_csv_filename))

'./../../data/raw/laposte/019HexaSmal-full.csv'

## Import Decrees

In [4]:


df = pd.read_parquet(os.path.join(processed_data_folder_name, decrees_filename))

In [5]:
df.isna().sum()

insee               0
nom_commune         0
debut_evenement     0
fin_evenement       0
date_arrete         0
date_parution_jo    0
nom_peril           0
code_peril          0
franchise           0
code_nor            0
decision            0
dtype: int64

In [6]:
df.head()

,insee,nom_commune,debut_evenement,fin_evenement,date_arrete,date_parution_jo,nom_peril,code_peril,franchise,code_nor,decision
43661,5063,LA GRAVE,2001-03-19,2001-03-25,2001-11-15,2001-12-01,Mouvement de Terrain,MVT,Simple,INTE0100649A,Reconnue
43662,5128,SAINT ANDRE D EMBRUN,2001-03-29,2001-03-29,2001-11-15,2001-12-01,Mouvement de Terrain,MVT,Simple,INTE0100649A,Reconnue
43663,6031,CANTARON,2000-11-23,2000-11-24,2001-11-15,2001-12-01,Mouvement de Terrain,MVT,Simple,INTE0100649A,Reconnue
43664,6031,CANTARON,2000-11-23,2000-11-24,2001-11-15,2001-12-01,Inondations et/ou Coulées de Boue,ICB,Simple,INTE0100649A,Reconnue
43665,6057,L'ESCARENE,2000-10-30,2000-10-31,2001-11-15,2001-12-01,Mouvement de Terrain,MVT,Simple,INTE0100649A,Reconnue

In [7]:
df['decision'].value_counts()

decision
Reconnue                                   130517
Reconnue(sans impact sur la modulation)     65206
Non reconnue                                39739
Name: count, dtype: int64

## Get Insee gps coodinates of communes.

In [12]:
communes_location = pd.read_csv(os.path.join(communes_folder_name, communes_csv_filename))

In [13]:
communes_location.head()

,#Code_commune_INSEE,Nom_de_la_commune,Code_postal,Libellé_d_acheminement,Ligne_5,_contours_commune.geometry
0,01001,L ABERGEMENT CLEMENCIAT,1400,L ABERGEMENT CLEMENCIAT,NaN,"{""type"":""Polygon"",""coordinates"":[[[4.9584116,4..."
1,01002,L ABERGEMENT DE VAREY,1640,L ABERGEMENT DE VAREY,NaN,"{""type"":""Polygon"",""coordinates"":[[[5.4302024,4..."
2,01004,AMBERIEU EN BUGEY,1500,AMBERIEU EN BUGEY,NaN,"{""type"":""Polygon"",""coordinates"":[[[5.4088198,4..."
3,01005,AMBERIEUX EN DOMBES,1330,AMBERIEUX EN DOMBES,NaN,"{""type"":""Polygon"",""coordinates"":[[[4.9429765,4..."
4,01006,AMBLEON,1300,AMBLEON,NaN,"{""type"":""Polygon"",""coordinates"":[[[5.5708254,4..."

In [14]:
communes_location.columns

Index(['#Code_commune_INSEE', 'Nom_de_la_commune', 'Code_postal',
       'Libellé_d_acheminement', 'Ligne_5', '_contours_commune.geometry'],
      dtype='object')

In [ ]:
#Code_commune_INSEE

In [10]:
communes_location.head()

,Code INSEE,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,geo_shape,ID Geofla,Code Commune,Code Canton,Code Arrondissement,Code Département,Code Région
0,59416,59190,MORBECQUE,['NORD'],['NORD-PAS-DE-CALAIS'],['Commune simple'],23.0,4455.0,2.7,"50.67689342861573, 2.536216144331492","{""coordinates"": [[[2.501239302134784, 50.63986...",1237,416,30,4,59,31
1,22102,22330,LANGOURLA,"[""COTES-D'ARMOR""]",['BRETAGNE'],['Commune simple'],170.0,2165.0,0.6,"48.284641107667674, -2.415501011324659","{""coordinates"": [[[-2.416298136623701, 48.2530...",10183,102,9,1,22,53
2,31225,31310,GOUTEVERNISSE,['HAUTE-GARONNE'],['MIDI-PYRENEES'],['Commune simple'],264.0,485.0,0.2,"43.214026301449536, 1.173765920286677","{""coordinates"": [[[1.165580460427912, 43.20037...",20555,225,27,1,31,73
3,23025,23220,BONNAT,['CREUSE'],['LIMOUSIN'],['Chef-lieu canton'],355.0,4554.0,1.3,"46.32301933418213, 1.913450631364578","{""coordinates"": [[[1.952331841746855, 46.28624...",3586,25,6,2,23,74
4,38522,38740,VALJOUFFREY,['ISERE'],['RHONE-ALPES'],['Commune simple'],2009.0,12644.0,0.1,"44.88153491127053, 6.07950399615059","{""coordinates"": [[[6.056489736635054, 44.81581...",1082,522,36,1,38,82

In [11]:
communes_location.isna().sum()

Code INSEE             0
Code Postal            0
Commune                0
Département            0
Région                 0
Statut                 0
Altitude Moyenne       0
Superficie             0
Population             0
geo_point_2d           0
geo_shape              0
ID Geofla              0
Code Commune           0
Code Canton            0
Code Arrondissement    0
Code Département       0
Code Région            0
dtype: int64

In [12]:
communes_location['Code INSEE'].is_unique

True

In [17]:
# Merge DataFrames based on 'insee'

merged_df = pd.merge(df, communes_location[['#Code_commune_INSEE', 'Code_postal',]],  left_on='insee', right_on='#Code_commune_INSEE', how='left')

In [14]:
df.shape

(235462, 11)

In [15]:
merged_df.shape

(235462, 28)

In [18]:
merged_df.isna().sum()

insee                      0
nom_commune                0
debut_evenement            0
fin_evenement              0
date_arrete                0
date_parution_jo           0
nom_peril                  0
code_peril                 0
franchise                  0
code_nor                   0
decision                   0
#Code_commune_INSEE    20546
Code_postal            20546
dtype: int64

In [17]:
merged_df

,insee,nom_commune,debut_evenement,fin_evenement,date_arrete,date_parution_jo,nom_peril,code_peril,franchise,code_nor,...,Superficie,Population,geo_point_2d,geo_shape,ID Geofla,Code Commune,Code Canton,Code Arrondissement,Code Département,Code Région
0,5063,LA GRAVE,2001-03-19,2001-03-25,2001-11-15,2001-12-01,Mouvement de Terrain,MVT,Simple,INTE0100649A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5128,SAINT ANDRE D EMBRUN,2001-03-29,2001-03-29,2001-11-15,2001-12-01,Mouvement de Terrain,MVT,Simple,INTE0100649A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6031,CANTARON,2000-11-23,2000-11-24,2001-11-15,2001-12-01,Mouvement de Terrain,MVT,Simple,INTE0100649A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6031,CANTARON,2000-11-23,2000-11-24,2001-11-15,2001-12-01,Inondations et/ou Coulées de Boue,ICB,Simple,INTE0100649A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6057,L'ESCARENE,2000-10-30,2000-10-31,2001-11-15,2001-12-01,Mouvement de Terrain,MVT,Simple,INTE0100649A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235457,90035,DORANS,2023-06-01,2023-09-30,2024-06-18,2024-07-02,Sécheresse,SEC,-,IOME2415881A,...,382.0,0.6,"47.58474462701379, 6.837247587105974","{""coordinates"": [[[6.821011292623255, 47.57432...",20508.0,35.0,10.0,1.0,90,43.0
235458,90039,ESSERT,2023-01-01,2023-12-31,2024-06-18,2024-07-02,Sécheresse,SEC,-,IOME2415881A,...,710.0,3.2,"47.63670149621771, 6.811982362490323","{""coordinates"": [[[6.807038927428798, 47.62266...",33825.0,39.0,6.0,1.0,90,43.0
235459,90045,FECHE L EGLISE,2023-07-01,2023-09-30,2024-06-18,2024-07-02,Sécheresse,SEC,-,IOME2415881A,...,399.0,0.8,"47.502176741594155, 6.955880312380269","{""coordinates"": [[[6.952446414801375, 47.48493...",25959.0,45.0,12.0,1.0,90,43.0
235460,90068,MEROUX MOVAL,2023-01-01,2023-10-31,2024-06-18,2024-07-02,Sécheresse,SEC,-,IOME2415881A,...,890.0,0.8,"47.59254610319736, 6.9095726149755095","{""coordinates"": [[[6.921865974123075, 47.57813...",14506.0,68.0,11.0,1.0,90,43.0
235461,90095,SUARCE,2023-10-01,2023-12-31,2024-06-18,2024-07-02,Sécheresse,SEC,Simple,IOME2415881A,...,1187.0,0.4,"47.56129565165385, 7.080055686636721","{""coordinates"": [[[7.066592750582137, 47.54205...",15419.0,95.0,13.0,1.0,90,43.0

In [19]:
merged_df_no_locations = merged_df[merged_df['Code INSEE'].isnull()]

In [22]:
merged_df_no_locations['debut_evenement'].max()

Timestamp('2024-05-24 00:00:00')

In [23]:
merged_df_no_locations['debut_evenement'].min()

Timestamp('1985-01-01 00:00:00')

In [24]:
merged_df_no_locations.head()

,insee,nom_commune,debut_evenement,fin_evenement,date_arrete,date_parution_jo,nom_peril,code_peril,franchise,code_nor,...,Superficie,Population,geo_point_2d,geo_shape,ID Geofla,Code Commune,Code Canton,Code Arrondissement,Code Département,Code Région
0,5063,LA GRAVE,2001-03-19,2001-03-25,2001-11-15,2001-12-01,Mouvement de Terrain,MVT,Simple,INTE0100649A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5128,SAINT ANDRE D EMBRUN,2001-03-29,2001-03-29,2001-11-15,2001-12-01,Mouvement de Terrain,MVT,Simple,INTE0100649A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6031,CANTARON,2000-11-23,2000-11-24,2001-11-15,2001-12-01,Mouvement de Terrain,MVT,Simple,INTE0100649A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6031,CANTARON,2000-11-23,2000-11-24,2001-11-15,2001-12-01,Inondations et/ou Coulées de Boue,ICB,Simple,INTE0100649A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6057,L'ESCARENE,2000-10-30,2000-10-31,2001-11-15,2001-12-01,Mouvement de Terrain,MVT,Simple,INTE0100649A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN